CREATE TABLE
  "public"."legacy_progress_note_job" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "created_by" UUID,
    "started_at" TIMESTAMP WITH TIME ZONE,
    "finished_at" TIMESTAMP WITH TIME ZONE,
    "status" TEXT NOT NULL DEFAULT 'Ready'::TEXT,
    "message" TEXT NOT NULL DEFAULT ''::TEXT,
    "case_id" BIGINT NOT NULL,
    "filepath" TEXT NOT NULL DEFAULT ''::TEXT,
    "xml" TEXT NOT NULL DEFAULT ''::TEXT,
    "item_total" BIGINT NOT NULL DEFAULT '0'::BIGINT,
    "dryrun" BOOLEAN NOT NULL
  );

ALTER TABLE "public"."legacy_progress_note_job" OWNER TO "postgres";

ALTER TABLE "public"."legacy_progress_note_job" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX legacy_progress_note_job_pkey ON public.legacy_progress_note_job USING btree (id);

ALTER TABLE "public"."legacy_progress_note_job"
ADD CONSTRAINT "legacy_progress_note_job_pkey" PRIMARY KEY USING INDEX "legacy_progress_note_job_pkey";

ALTER TABLE "public"."legacy_progress_note_job"
ADD CONSTRAINT "public_legacy_progress_note_job_case_id_fkey" FOREIGN KEY (case_id) REFERENCES "case" (id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."legacy_progress_note_job" VALIDATE CONSTRAINT "public_legacy_progress_note_job_case_id_fkey";

ALTER TABLE "public"."legacy_progress_note_job"
ADD CONSTRAINT "public_legacy_progress_note_job_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."legacy_progress_note_job" VALIDATE CONSTRAINT "public_legacy_progress_note_job_created_by_fkey";

CREATE POLICY "Enable insert for all users" ON "public"."legacy_progress_note_job" AS permissive FOR INSERT TO authenticated
WITH
  CHECK (TRUE);

CREATE POLICY "Enable update for all users" ON "public"."legacy_progress_note_job" AS permissive FOR
UPDATE TO authenticated USING (TRUE);