CREATE TABLE
  "public"."legacy_progress_note" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "case_id" BIGINT NOT NULL,
    "row_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "entered_at" TEXT NOT NULL,
    "entered_by" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Draft'::TEXT,
    "entered_at_date" TIMESTAMP WITH TIME ZONE,
    "entered_by_uuid" UUID,
    "tags" TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
    "accepted_at" TIMESTAMP WITH TIME ZONE,
    "accepted_by" UUID,
    "accepted_by_name" TEXT
  );

ALTER TABLE "public"."legacy_progress_note" OWNER TO "postgres";

ALTER TABLE "public"."legacy_progress_note" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."progress_note"
ADD COLUMN "import_record_id" BIGINT;

ALTER TABLE "public"."progress_note"
ADD COLUMN "imported_at" TIMESTAMP WITH TIME ZONE;

ALTER TABLE "public"."progress_note"
ADD COLUMN "imported_by" UUID;

ALTER TABLE "public"."progress_note"
ADD COLUMN "imported_by_name" TEXT;

CREATE UNIQUE INDEX legacy_progress_note_pkey ON public.legacy_progress_note USING btree (id);

ALTER TABLE "public"."legacy_progress_note"
ADD CONSTRAINT "legacy_progress_note_pkey" PRIMARY KEY USING INDEX "legacy_progress_note_pkey";

ALTER TABLE "public"."legacy_progress_note"
ADD CONSTRAINT "public_legacy_progress_note_case_id_fkey" FOREIGN KEY (case_id) REFERENCES "case" (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."legacy_progress_note" VALIDATE CONSTRAINT "public_legacy_progress_note_case_id_fkey";

ALTER TABLE "public"."legacy_progress_note"
ADD CONSTRAINT "public_legacy_progress_note_entered_by_uuid_fkey" FOREIGN KEY (entered_by_uuid) REFERENCES team_member (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."legacy_progress_note" VALIDATE CONSTRAINT "public_legacy_progress_note_entered_by_uuid_fkey";

ALTER TABLE "public"."progress_note"
ADD CONSTRAINT "public_progress_note_import_record_id_fkey" FOREIGN KEY (import_record_id) REFERENCES legacy_progress_note (id) ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."progress_note" VALIDATE CONSTRAINT "public_progress_note_import_record_id_fkey";

ALTER TABLE "public"."progress_note"
ADD CONSTRAINT "public_progress_note_imported_by_fkey" FOREIGN KEY (imported_by) REFERENCES auth.users (id) NOT VALID;

ALTER TABLE "public"."progress_note" VALIDATE CONSTRAINT "public_progress_note_imported_by_fkey";

CREATE POLICY "Enable all for all users" ON "public"."legacy_progress_note" AS permissive FOR ALL TO authenticated USING (TRUE);