CREATE TABLE
  "public"."rollover_job" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "created_by" UUID NOT NULL,
    "created_by_name" TEXT NOT NULL DEFAULT ''::TEXT,
    "started_at" TIMESTAMP WITH TIME ZONE,
    "finished_at" TIMESTAMP WITH TIME ZONE,
    "item_total" BIGINT NOT NULL DEFAULT '0'::BIGINT,
    "item_not_done" INTEGER NOT NULL DEFAULT 0,
    "item_done_ok" INTEGER NOT NULL DEFAULT 0,
    "item_done_error" INTEGER NOT NULL DEFAULT 0,
    "status" TEXT NOT NULL DEFAULT 'Ready'::TEXT
  );

ALTER TABLE "public"."rollover_job" OWNER TO "postgres";

ALTER TABLE "public"."rollover_job" ENABLE ROW LEVEL SECURITY;

CREATE TABLE
  "public"."rollover_job_item" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "job_id" BIGINT NOT NULL,
    "case_id" BIGINT NOT NULL,
    "case_status" TEXT NOT NULL DEFAULT ''::TEXT,
    "started_at" TIMESTAMP WITH TIME ZONE,
    "finished_at" TIMESTAMP WITH TIME ZONE,
    "done_ok" BOOLEAN,
    "message" TEXT,
    "student_name" TEXT NOT NULL DEFAULT ''::TEXT,
    "student_no" TEXT NOT NULL DEFAULT ''::TEXT
  );

ALTER TABLE "public"."rollover_job_item" OWNER TO "postgres";

ALTER TABLE "public"."rollover_job_item" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX rollover_job_item_pkey ON public.rollover_job_item USING btree (id);

CREATE UNIQUE INDEX rollover_job_pkey ON public.rollover_job USING btree (id);

ALTER TABLE "public"."rollover_job"
ADD CONSTRAINT "rollover_job_pkey" PRIMARY KEY USING INDEX "rollover_job_pkey";

ALTER TABLE "public"."rollover_job_item"
ADD CONSTRAINT "rollover_job_item_pkey" PRIMARY KEY USING INDEX "rollover_job_item_pkey";

ALTER TABLE "public"."rollover_job"
ADD CONSTRAINT "public_rollover_job_created_by_fkey" FOREIGN KEY (created_by) REFERENCES auth.users (id) NOT VALID;

ALTER TABLE "public"."rollover_job" VALIDATE CONSTRAINT "public_rollover_job_created_by_fkey";

ALTER TABLE "public"."rollover_job_item"
ADD CONSTRAINT "public_rollover_job_item_case_id_fkey" FOREIGN KEY (case_id) REFERENCES "case" (id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."rollover_job_item" VALIDATE CONSTRAINT "public_rollover_job_item_case_id_fkey";

ALTER TABLE "public"."rollover_job_item"
ADD CONSTRAINT "public_rollover_job_item_job_id_fkey" FOREIGN KEY (job_id) REFERENCES rollover_job (id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;

ALTER TABLE "public"."rollover_job_item" VALIDATE CONSTRAINT "public_rollover_job_item_job_id_fkey";