CREATE TABLE
  "public"."remark" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    "original_created_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "original_created_by" TEXT NOT NULL,
    "original_updated_at" TIMESTAMP WITH TIME ZONE NOT NULL,
    "student_no" TEXT NOT NULL,
    "remark_level" SMALLINT NOT NULL,
    "category" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "attachment" TEXT,
    "dms_json" jsonb
  );

ALTER TABLE "public"."remark" OWNER TO "postgres";

ALTER TABLE "public"."remark" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."case"
ADD COLUMN "specialists" BIGINT[] NOT NULL DEFAULT '{}'::BIGINT[];

CREATE UNIQUE INDEX remark_pkey ON public.remark USING btree (id);

ALTER TABLE "public"."remark"
ADD CONSTRAINT "remark_pkey" PRIMARY KEY USING INDEX "remark_pkey";

GRANT DELETE ON TABLE "public"."remark" TO "anon";

GRANT INSERT ON TABLE "public"."remark" TO "anon";

GRANT REFERENCES ON TABLE "public"."remark" TO "anon";

GRANT
SELECT
  ON TABLE "public"."remark" TO "anon";

GRANT TRIGGER ON TABLE "public"."remark" TO "anon";

GRANT
TRUNCATE ON TABLE "public"."remark" TO "anon";

GRANT
UPDATE ON TABLE "public"."remark" TO "anon";

GRANT DELETE ON TABLE "public"."remark" TO "authenticated";

GRANT INSERT ON TABLE "public"."remark" TO "authenticated";

GRANT REFERENCES ON TABLE "public"."remark" TO "authenticated";

GRANT
SELECT
  ON TABLE "public"."remark" TO "authenticated";

GRANT TRIGGER ON TABLE "public"."remark" TO "authenticated";

GRANT
TRUNCATE ON TABLE "public"."remark" TO "authenticated";

GRANT
UPDATE ON TABLE "public"."remark" TO "authenticated";

GRANT DELETE ON TABLE "public"."remark" TO "service_role";

GRANT INSERT ON TABLE "public"."remark" TO "service_role";

GRANT REFERENCES ON TABLE "public"."remark" TO "service_role";

GRANT
SELECT
  ON TABLE "public"."remark" TO "service_role";

GRANT TRIGGER ON TABLE "public"."remark" TO "service_role";

GRANT
TRUNCATE ON TABLE "public"."remark" TO "service_role";

GRANT
UPDATE ON TABLE "public"."remark" TO "service_role";