--
-- Data for Name: role_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--
TRUNCATE TABLE "public"."role_permission";

INSERT INTO
  "public"."role_permission" ("role", "permission")
VALUES
  ('IT Admin', 'dashboard:list'),
  ('IT Admin', 'case:list'),
  ('IT Admin', 'my_case:list'),
  ('GLL', 'dashboard:list'),
  ('GLL', 'case:list'),
  ('GLL', 'my_case:list'),
  ('GLL', 'progress_note:list'),
  ('GLL', 'progress_note:create'),
  ('GLL', 'progress_note:edit'),
  ('GLL', 'progress_note:delete'),
  ('GLL', 'reminder:list'),
  ('GLL', 'reminder:create'),
  ('GLL', 'reminder:edit'),
  ('GLL', 'reminder:delete'),
  ('GLL', 'session:list'),
  ('GLL', 'session:create'),
  ('GLL', 'session:edit'),
  ('GLL', 'session:delete'),
  ('GLL', 'target:list'),
  ('GLL', 'target:create'),
  ('GLL', 'target:edit'),
  ('GLL', 'target:delete'),
  ('GLL', 'remark:list'),
  ('Nurse', 'dashboard:list'),
  ('Nurse', 'case:list'),
  ('Nurse', 'case:edit'),
  ('Nurse', 'my_case:list'),
  ('Nurse', 'progress_note:list'),
  ('Nurse', 'progress_note:create'),
  ('Nurse', 'reminder:list'),
  ('Nurse', 'reminder:create'),
  ('Nurse', 'session:list'),
  ('Nurse', 'session:create'),
  ('Nurse', 'target:list'),
  ('Nurse', 'target:create'),
  ('Nurse', 'remark:list'),
  ('Li Ren Leadership', 'dashboard:list'),
  ('Li Ren Leadership', 'case:list'),
  ('Li Ren Leadership', 'case:create'),
  ('Li Ren Leadership', 'case:edit'),
  ('Li Ren Leadership', 'case:audit'),
  ('Li Ren Leadership', 'my_case:list'),
  ('Li Ren Leadership', 'progress_note:list'),
  ('Li Ren Leadership', 'progress_note:create'),
  ('Li Ren Leadership', 'progress_note:edit'),
  ('Li Ren Leadership', 'progress_note:delete'),
  ('Li Ren Leadership', 'reminder:list'),
  ('Li Ren Leadership', 'reminder:create'),
  ('Li Ren Leadership', 'reminder:edit'),
  ('Li Ren Leadership', 'reminder:delete'),
  ('Li Ren Leadership', 'session:list'),
  ('Li Ren Leadership', 'session:create'),
  ('Li Ren Leadership', 'session:edit'),
  ('Li Ren Leadership', 'session:delete'),
  ('Li Ren Leadership', 'target:list'),
  ('Li Ren Leadership', 'target:create'),
  ('Li Ren Leadership', 'target:edit'),
  ('Li Ren Leadership', 'target:delete'),
  ('Li Ren Leadership', 'remark:list'),
  ('Li Ren GLS', 'dashboard:list'),
  ('Li Ren GLS', 'case:list'),
  ('Li Ren GLS', 'case:create'),
  ('Li Ren GLS', 'case:edit'),
  ('Li Ren GLS', 'case:audit'),
  ('Li Ren GLS', 'my_case:list'),
  ('Li Ren GLS', 'progress_note:list'),
  ('Li Ren GLS', 'progress_note:create'),
  ('Li Ren GLS', 'reminder:list'),
  ('Li Ren GLS', 'reminder:create'),
  ('Li Ren GLS', 'session:list'),
  ('Li Ren GLS', 'session:create'),
  ('Li Ren GLS', 'target:list'),
  ('Li Ren GLS', 'target:create'),
  ('Li Ren GLS', 'remark:list'),
  ('Li Ren Contact', 'dashboard:list'),
  ('Li Ren Contact', 'case:list'),
  ('Li Ren Contact', 'case:create'),
  ('Li Ren Contact', 'my_case:list'),
  ('Li Ren Contact', 'progress_note:list'),
  ('Li Ren Contact', 'progress_note:create'),
  ('Li Ren Contact', 'reminder:list'),
  ('Li Ren Contact', 'reminder:create'),
  ('Li Ren Contact', 'session:list'),
  ('Li Ren Contact', 'session:create'),
  ('Li Ren Contact', 'target:list'),
  ('Li Ren Contact', 'target:create'),
  ('Li Ren Contact', 'remark:list'),
  ('Li Ren Leadership', 'case_handler:edit'),
  ('Li Ren GLS', 'case_handler:edit'),
  ('Li Ren Leadership', 'case_handler:create'),
  ('Li Ren GLS', 'case_handler:create'),
  ('Li Ren Leadership', 'case_handler:delete'),
  ('Li Ren GLS', 'case_handler:delete'),
  ('GLL', 'page:list'),
  ('Nurse', 'page:list'),
  ('Li Ren Leadership', 'page:list'),
  ('Li Ren GLS', 'page:list'),
  ('Li Ren Contact', 'page:list'),
  ('GLL', 'page:create'),
  ('Li Ren Leadership', 'page:create'),
  ('GLL', 'page:edit'),
  ('Li Ren Leadership', 'page:edit'),
  ('GLL', 'page:delete'),
  ('Li Ren Leadership', 'page:delete'),
  ('GLL', 'specialist:list'),
  ('Nurse', 'specialist:list'),
  ('Li Ren Leadership', 'specialist:list'),
  ('Li Ren GLS', 'specialist:list'),
  ('Li Ren Contact', 'specialist:list'),
  ('Li Ren Leadership', 'specialist:create'),
  ('Li Ren Contact', 'specialist:create'),
  ('Li Ren GLS', 'specialist:create'),
  ('Li Ren Leadership', 'specialist:edit'),
  ('Li Ren GLS', 'specialist:edit'),
  ('Li Ren Contact', 'specialist:edit'),
  ('Li Ren Leadership', 'specialist:delete'),
  ('Li Ren GLS', 'specialist:delete'),
  ('Li Ren Contact', 'specialist:delete'),
  ('IT Admin', 'pending_member:list'),
  ('Li Ren Leadership', 'pending_member:list'),
  ('IT Admin', 'pending_member:create'),
  ('Li Ren Leadership', 'pending_member:create'),
  ('IT Admin', 'pending_member:edit'),
  ('Li Ren Leadership', 'pending_member:edit'),
  ('IT Admin', 'pending_member:delete'),
  ('Li Ren Leadership', 'pending_member:delete'),
  ('IT Admin', 'team_member:list'),
  ('Li Ren Leadership', 'team_member:list'),
  ('IT Admin', 'team_member:create'),
  ('Li Ren Leadership', 'team_member:create'),
  ('IT Admin', 'team_member:edit'),
  ('Li Ren Leadership', 'team_member:edit'),
  ('Li Ren GLS', 'page:create'),
  ('Li Ren Contact', 'case_handler:create'),
  ('Li Ren Contact', 'case_handler:edit'),
  ('Li Ren Contact', 'case_handler:delete'),
  ('IT Admin', 'team_member:ban'),
  ('Li Ren Leadership', 'team_member:ban'),
  ('IT Admin', 'team_member:unban'),
  ('Li Ren Leadership', 'team_member:unban'),
  ('Li Ren Leadership', 'rollover_job:list'),
  ('Li Ren Leadership', 'rollover_job:create'),
  ('Li Ren Leadership', 'safeguarding_note:create'),
  ('GLL', 'safeguarding_note:create'),
  ('Li Ren GLS', 'safeguarding_note:create'),
  ('Li Ren Contact', 'safeguarding_note:create'),
  ('Li Ren Leadership', 'safeguarding_note:delete'),
  ('GLL', 'safeguarding_note:delete'),
  ('Li Ren GLS', 'safeguarding_note:delete'),
  ('Li Ren Contact', 'safeguarding_note:delete'),
  ('Li Ren Leadership', 'safeguarding_note:edit'),
  ('GLL', 'safeguarding_note:edit'),
  ('Li Ren GLS', 'safeguarding_note:edit'),
  ('Li Ren Contact', 'safeguarding_note:edit'),
  ('Li Ren Leadership', 'safeguarding_note:list'),
  ('GLL', 'safeguarding_note:list'),
  ('Li Ren GLS', 'safeguarding_note:list'),
  ('Li Ren Contact', 'safeguarding_note:list'),
  ('Li Ren Leadership', 'safeguarding_note:read_all'),
  ('GLL', 'safeguarding_note:read_all'),
  ('Li Ren GLS', 'safeguarding_note:read_all');