# Use the official Node.js 18.19.0 image as the base image
FROM node:18.19.0

# Set the working directory inside the container
WORKDIR /app

# Install dbmate globally using npm
RUN npm install -g dbmate

# Specify any additional configurations or commands as needed

# Set the command to run your application, if applicable
# CMD [ "npm", "start" ]
